# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-03 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name=b'ip')),
                ('osname', models.CharField(blank=True, choices=[(b'1', b'linux'), (b'2', b'windows'), (b'3', b'other')], max_length=20, null=True, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe5\x90\x8d\xe7\xa7\xb0')),
                ('prartition', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'\xe5\x88\x86\xe5\x8c\xba\xe6\x83\x85\xe5\x86\xb5\xe6\x8f\x8f\xe8\xbf\xb0')),
            ],
        ),
    ]
