# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-21 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name=b'\xe7\xa3\x81\xe7\x9b\x98\xe4\xbd\xbf\xe7\x94\xa8\xe7\x8e\x87')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe5\xbd\x95\xe5\x85\xa5\xe6\x97\xb6\xe9\x97\xb4')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_application.HostInfo')),
            ],
        ),
    ]
